// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeiDgSFESRJ6PKSPNg4Jio9Wi5fWqcTYE',
    appId: '1:248568937026:web:b3a8a03ed24b7e9e6acbdb',
    messagingSenderId: '248568937026',
    projectId: 'parking-slot-339c5',
    authDomain: 'parking-slot-339c5.firebaseapp.com',
    storageBucket: 'parking-slot-339c5.firebasestorage.app',
    measurementId: 'G-9MBPLN7D9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3pYYMXR8ZK39dS7a9rHHtQZHz2e4Vdzw',
    appId: '1:248568937026:android:a82429773a98c3db6acbdb',
    messagingSenderId: '248568937026',
    projectId: 'parking-slot-339c5',
    storageBucket: 'parking-slot-339c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBICgD4IixY2FOdOSUrLtnXYHLeQoK2PXM',
    appId: '1:248568937026:ios:aaaca69401d20ee46acbdb',
    messagingSenderId: '248568937026',
    projectId: 'parking-slot-339c5',
    storageBucket: 'parking-slot-339c5.firebasestorage.app',
    iosBundleId: 'com.example.parkingSlot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBICgD4IixY2FOdOSUrLtnXYHLeQoK2PXM',
    appId: '1:248568937026:ios:aaaca69401d20ee46acbdb',
    messagingSenderId: '248568937026',
    projectId: 'parking-slot-339c5',
    storageBucket: 'parking-slot-339c5.firebasestorage.app',
    iosBundleId: 'com.example.parkingSlot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeiDgSFESRJ6PKSPNg4Jio9Wi5fWqcTYE',
    appId: '1:248568937026:web:8e2d16f1ff93cc466acbdb',
    messagingSenderId: '248568937026',
    projectId: 'parking-slot-339c5',
    authDomain: 'parking-slot-339c5.firebaseapp.com',
    storageBucket: 'parking-slot-339c5.firebasestorage.app',
    measurementId: 'G-C6SV871R3W',
  );
}
